### PR TITLE
Feature/fast hoppers

### PR DESCRIPTION
**Pull request by Phoenix616**

### CODE REVIEW

**Comment by TNTUP** [comment]
As I can't make "issues" here but I'll comment if you can change something, existent /lib/native/Linux/amd64/libsqlitejdbc.so throws an error about org.sqlite.NativeDB not found due to this .so library. I deleted it, it redownloaded the sqlite.jar (seems not to make issues in 1.11) but it tried redownloading the .so library, the file is created but empty. Now there's the UnsatifiedLinkError, file too short due its 0 bytes. I guess its better removing the automatic download (or I can fork and removing from myself). Also the Java VM warning: http://i.qcfb.ca/201611171847847.png (doesn't include in latest.log so I have screenshotted it)

Btw,. thanks for this fork when I had hoppers issues, very nice from you :P

**Comment by Phoenix616** [comment]
This has nothing to do with my fast hopper feature? Please refer to the main repo when reporting bugs not related to our changes. (There is [an issue](https://github.com/Hidendra/LWC/issues/953) open there about that) Also I personally have little to no interest in the SQLLite feature as I run the plugin with a MySQL backend.

**Comment by Phoenix616** [comment]
I will also probably stop maintaining this fork in the near future as this "feature" shouldn't really be implemented by plugins but fixed directly by the server. (see [my ticket for cb/spigot](https://hub.spigotmc.org/jira/browse/SPIGOT-2731) and my [pull request for paper](https://github.com/PaperMC/Paper/pull/445) on that matter)

**Comment by TNTUP** [comment]
I'm sorry but I couldn't make an issue, it does not exist here. Hidendra is inactive, I've opted messaging you directly than him. Anyway I've solved it myself by emptying the .so file. Sorry again

**Pull request merged**
